# Use root/example as user/password credentials
version: '3.1'

services:
  h2-server:
    image: augur/h2:1.14.200
    container_name: h2-server
    restart: always
    networks:
      - db-net
    volumes:
      - ./conf/h2.server.properties:/root/.h2.server.properties
      - ./data:/opt/h2/data
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8082:8082"
      - "9092:9092"